const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    CLOSE_CART_OVERLAY: 'CLOSE_CART_OVERLAY',
    ADD_PRODUCT: 'ADD_PRODUCT',
    REMOVE_ITEM: 'REMOVE_ITEM',
}

export default CartActionTypes;