const CurrencyActionTypes = {
    TOGGLE_CURRENCY_HIDDEN: "TOGGLE_CURRENCY_HIDDEN",
    ADD_CURRENCIES : "ADD_CURRENCIES",
    SWITCH_CURRENCIES: 'SWITCH_CURRENCIES',
    CURRENCY_INDEX: 'CURRENCY_INDEX'
};

export default CurrencyActionTypes;